ALTER TYPE "PendingActionStatus" ADD VALUE IF NOT EXISTS 'EXECUTING';
ALTER TYPE "PendingActionStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "PendingActionStatus" ADD VALUE IF NOT EXISTS 'FAILED';
